//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.03 at 09:37:03 AM CEST 
//


package eu.trentorise.smartcampus.resourceprovider.jaxbmodel;

import java.util.Collections;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

import org.springframework.util.StringUtils;
import org.springframework.web.util.UriTemplate;


/**
 * <p>Java class for resourceMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class ResourceMapping {

    @XmlAttribute
    protected String uri;
    @XmlAttribute
    protected String pathPattern;
    @XmlAttribute
    protected String method;

    private UriTemplate uriTemplate = null;
    private UriTemplate pathTemplate = null;
    
    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }
  
	public String getPathPattern() {
		return pathPattern;
	}

	public void setPathPattern(String pathPattern) {
		this.pathPattern = pathPattern;
	}

	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Set<String> getMethods() {
		if (method == null) return Collections.emptySet();	
		return StringUtils.commaDelimitedListToSet(method);
	}
	
	public UriTemplate getUriTemplate() {
		if (uriTemplate == null)  {
			uriTemplate = new UriTemplate(uri);
		}
		return uriTemplate;
	}
	
	public UriTemplate getPathTemplate() {
		if (pathTemplate == null)  {
			pathTemplate = new UriTemplate(pathPattern);
		}
		return pathTemplate;
	}
	
}
